version: '3.7'
services:
    node-server:
        container_name: grepo-tools_server
        build: ./
        networks:
            default:
                ipv4_address: 192.168.1.82
        restart: on-failure
        
networks:
    default:
        external:
            name: macvlan