version: '3.7'
services:
    grepo-tools-server:
        container_name: grepo-tools-server
        build: ./
        ports:
            - 9000:9000
        networks:
            default:
                ipv4_address: 192.168.1.82
        restart: on-failure
        
networks:
    default:
        external:
            name: macvlan