version: '3.8'
services:
    # vue-client:
    #     container_name: grepo-tools-client
    #     build: ./client
    #     ports:
    #         - 8080:8080
    #     restart: on-failure

    node-server:
        container_name: grepo-tools-server
        build: ./server
        networks:
            default:
                ipv4_address: 192.168.1.82
        restart: on-failure
        
networks:
    default:
        external:
            name: macvlan